import type { Metadata } from "next";
import "../public/assets/css/soft-ui-dashboard.css";
import "../public/assets/css/nucleo-icons.css";
import "./globals.css";
// import Footer from "./components/Footer";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
          integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className="g-sidenav-show  bg-gray-100">
        <Header />
        <main className="main-content container p-0">
          <div className="conatiner p-4">{children}</div>
          {/* <Footer /> */}
        </main>
      </body>
    </html>
  );
}
